name: toc
channels:
  - defaults
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
dependencies:
  - bzip2=1.0.8=h80987f9_6
  - ca-certificates=2025.11.4=hca03da5_0
  - expat=2.7.3=h982b769_0
  - libcxx=20.1.8=hd7fd590_1
  - libffi=3.4.4=hca03da5_1
  - libzlib=1.3.1=h5f15de7_0
  - ncurses=6.5=hee39554_0
  - openssl=3.0.18=h9b4081a_0
  - pip=25.3=pyhc872135_0
  - python=3.11.14=hf701271_0
  - readline=8.3=h0b18652_0
  - setuptools=80.9.0=py311hca03da5_0
  - sqlite=3.51.0=hab6afd1_0
  - tk=8.6.15=hcd8a7d5_0
  - wheel=0.45.1=py311hca03da5_0
  - xz=5.6.4=h80987f9_1
  - zlib=1.3.1=h5f15de7_0
  - pip:
      - aiohappyeyeballs==2.6.1
      - aiohttp==3.13.2
      - aiosignal==1.4.0
      - annotated-types==0.7.0
      - anyio==4.11.0
      - apple-certifi==2.3.3
      - apple-interlinked==1.1.141
      - attrs==25.4.0
      - backoff==2.2.1
      - beautifulsoup4==4.14.2
      - blis==1.3.2
      - catalogue==2.0.10
      - certifi==2025.11.12
      - charset-normalizer==3.4.4
      - click==8.3.0
      - cloudpathlib==0.23.0
      - confection==0.1.5
      - cymem==2.0.13
      - datasets==4.4.1
      - dill==0.4.0
      - distro==1.9.0
      - docutils==0.22.3
      - filelock==3.20.0
      - frozenlist==1.8.0
      - fsspec==2025.10.0
      - grpcio==1.76.0
      - h11==0.16.0
      - h2==4.3.0
      - hf-xet==1.2.0
      - hpack==4.1.0
      - httpcore==1.0.9
      - httpx==0.28.1
      - huggingface-hub==0.36.0
      - hyperframe==6.1.0
      - idna==3.11
      - jinja2==3.1.6
      - jiter==0.12.0
      - joblib==1.5.2
      - markdown2==2.5.4
      - markupsafe==3.0.3
      - mpmath==1.3.0
      - multidict==6.7.0
      - multiprocess==0.70.18
      - murmurhash==1.0.15
      - networkx==3.5
      - numpy==2.3.4
      - openai==2.8.0
      - packaging==25.0
      - pandas==2.3.3
      - pillow==12.0.0
      - portalocker==3.2.0
      - preshed==3.0.11
      - propcache==0.4.1
      - protobuf==6.33.1
      - pyarrow==22.0.0
      - pydantic==2.12.4
      - pydantic-core==2.41.5
      - python-dateutil==2.9.0.post0
      - pytz==2025.2
      - pyyaml==6.0.3
      - qdrant-client==1.15.1
      - regex==2025.11.3
      - requests==2.32.5
      - safetensors==0.6.2
      - scikit-learn==1.7.2
      - scipy==1.16.3
      - sentence-transformers==5.1.2
      - shellingham==1.5.4
      - six==1.17.0
      - smart-open==7.5.0
      - sniffio==1.3.1
      - soupsieve==2.8
      - spacy==3.8.9
      - spacy-legacy==3.0.12
      - spacy-loggers==1.0.5
      - srsly==2.5.1
      - sympy==1.14.0
      - thinc==8.3.9
      - threadpoolctl==3.6.0
      - tokenizers==0.22.1
      - torch==2.9.1
      - tqdm==4.67.1
      - transformers==4.57.1
      - typer-slim==0.20.0
      - typing-extensions==4.15.0
      - typing-inspection==0.4.2
      - tzdata==2025.2
      - ujson==5.11.0
      - urllib3==2.5.0
      - wasabi==1.1.3
      - weasel==0.4.3
      - websockets==15.0.1
      - wikiextractor==3.0.6
      - wrapt==2.0.1
      - xxhash==3.6.0
      - yarl==1.22.0
